/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a CardsAdaptor -c cardsadaptor -i cardshelper.h -l CardsHelper org.qt.policykit.qtcards.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "CardsAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class cardsadaptor
 */

cardsadaptor::cardsadaptor(CardsHelper *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

cardsadaptor::~cardsadaptor()
{
    // destructor
}

int cardsadaptor::write(QString &msg)
{
    // handle method call org.qt.policykit.qtcards.write
    return parent()->write(msg);
}

