/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a CardsAdaptor -c cardsadaptor -i cardshelper.h -l CardsHelper org.qt.policykit.qtcards.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CARDSADAPTOR_H
#define CARDSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "cardshelper.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.qt.policykit.qtcards
 */
class cardsadaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.qt.policykit.qtcards")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.qt.policykit.qtcards\">\n"
"    <method name=\"write\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"code\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"msg\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    cardsadaptor(CardsHelper *parent);
    virtual ~cardsadaptor();

    inline CardsHelper *parent() const
    { return static_cast<CardsHelper *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int write(QString &msg);
Q_SIGNALS: // SIGNALS
};

#endif
